## Time Elastic Kernels


In [7]:
# workspace utilities
import numpy as np
import dfrechet as df
import dtw
import processMobisig as pm

## Levenshtein's distance of the strings "aBigRedHat" and "aRedBigHat". 
Draw the alignment matrix to evaluate the pairwise Levenshtein's distance of the strings "aBigRedHat" and "aRedBigHat" using the following cost:
- i. deletion/insertion = 1, 
- ii. substition = 2, 
- iii. match = 0.
Document your observations.

In [ ]:
import re, ast
import pandas as pd

In [19]:
# function to compute the levenshtein's
import numpy as np

def min_ed_dis(first,second):
    #build an empty matrix of correct size
    first = [k for k in first]
    second = [k for k in second]
    matrix = np.zeros((len(first),len(second)))
    
    #first row & column
    matrix[0] = [j for j in range(len(first))]
    matrix[:,0] = [j for j in range(len(second))]
    
    #add anchor value
    if first[1] != second[1]:
        matrix[1,1] = 2
        
    #through every column
    for c in range(1, len(first)):
        #through every row
        for r in range(1, len(second)):
            
            #not same letter
            if first[c] != second[r]:
                matrix[r,c] = min(matrix[r-1, c], matrix[r, c-1])+2
            
            #same letter
            else:
                matrix[r,c] = matrix[r-1,c-1]
    return matrix

In [20]:
a = 'aBigRedHat'
b = 'aRedBigHat'

print("Levenshtein's distance: \n", min_ed_dis(a, b))

Levenshtein's distance: 
 [[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  3.  4.  5.  3.  5.  7.  9. 10. 11.]
 [ 2.  4.  6.  7.  5.  3.  5.  7.  9. 11.]
 [ 3.  5.  7.  9.  7.  5.  3.  5.  7.  9.]
 [ 4.  3.  5.  7.  9.  7.  5.  7.  9. 11.]
 [ 5.  5.  3.  5.  7.  9.  7.  9. 11. 13.]
 [ 6.  7.  5.  3.  5.  7.  9. 11. 13. 15.]
 [ 7.  9.  7.  5.  7.  9. 11.  9. 11. 13.]
 [ 8. 10.  9.  7.  9. 11. 13. 11.  9. 11.]
 [ 9. 11. 11.  9. 11. 13. 15. 13. 11.  9.]]


Levenstein's distance observation::: 
What do you observe in the matrix

Evaluating the 'time-elastic' distances of some time-series signature